#pragma once

#define ROVER_ENA_PIN 3
#define ROVER_IN1_PIN 4
#define ROVER_IN2_PIN 5
#define ROVER_ENB_PIN 6
#define ROVER_IN3_PIN 8
#define ROVER_IN4_PIN 7

#define ROVER_MAX_DISTANCE_CM 400
#define ROVER_SONAR_TRIG_PIN 9
#define ROVER_SONAR_ECHO_PIN 10

#define ROVER_TURNING_DISTANCE 100
#define ROVER_TURNING_SPEED 100
#define ROVER_MOVING_SPEED 150
